# Generated by Django 5.2.4 on 2025-08-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('axflo_app', '0003_alter_jobapplication_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='education',
            field=models.CharField(blank=True, choices=[('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('phd', 'PhD'), ('professional', 'Professional Certification')], max_length=20),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='experience',
            field=models.CharField(blank=True, choices=[('0-2', '0-2 years'), ('3-5', '3-5 years'), ('6-10', '6-10 years'), ('10+', '10+ years')], max_length=10),
        ),
    ]
